# Generated by Django 4.0.6 on 2022-12-17 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_name', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('batch_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='Frontend/src/Assests/Domains', verbose_name='domain image')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True, unique=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('img', models.FileField(upload_to='Frontend/src/Assests/Advisors', verbose_name='advisor images')),
                ('role', models.CharField(default='Advisor', max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('DOB', models.DateField(null=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('Batch', models.CharField(max_length=150, null=True)),
                ('Date_of_joining', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.JSONField(null=True)),
                ('week', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('Batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.batch')),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.domain')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
