# Generated by Django 4.0.6 on 2022-12-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.FileField(null=True, upload_to='Frontend/src/Assests/Advisors', verbose_name='advisor images'),
        ),
    ]
