# Generated by Django 4.0.6 on 2022-12-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_users_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Batch',
        ),
    ]
