# Generated by Django 4.0.6 on 2022-12-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_allocate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('task', models.CharField(max_length=150, null=True)),
                ('updates', models.CharField(max_length=150, null=True)),
                ('reviewer_name', models.CharField(max_length=150, null=True)),
                ('advisor_name', models.CharField(max_length=150, null=True)),
                ('score_1', models.IntegerField(default=0)),
                ('Extra_workout', models.CharField(max_length=150, null=True)),
                ('score_2', models.IntegerField(default=0)),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('eng_rev', models.CharField(max_length=150, null=True)),
                ('score_3', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
