# Generated by Django 4.0.6 on 2023-01-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.week'),
        ),
    ]
