# Generated by Django 4.0.6 on 2023-01-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_eng_rev_manifest_englist_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='englist_review',
            new_name='english_review',
        ),
    ]
