# Generated by Django 4.0.6 on 2023-01-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_englist_review_manifest_english_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.domain'),
        ),
    ]
