# Generated by Django 4.0.6 on 2023-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_allocate_advisor_alter_allocate_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='staff',
        ),
        migrations.AddField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
