# Generated by Django 4.0.6 on 2023-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_remove_users_staff_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
