# Generated by Django 4.0.6 on 2023-01-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students', '0006_remove_messages_receiver_remove_messages_sender_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('father_contact', models.CharField(max_length=200, null=True)),
                ('mother_name', models.CharField(max_length=200, null=True)),
                ('mother_contact', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(null=True)),
                ('village', models.CharField(max_length=200, null=True)),
                ('taluk', models.CharField(max_length=200, null=True)),
                ('education_qualification', models.CharField(max_length=200, null=True)),
                ('collage_or_school', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
