# Generated by Django 4.0.6 on 2023-01-01 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.CharField(max_length=150, null=True)),
                ('week2', models.CharField(max_length=150, null=True)),
                ('week3', models.CharField(max_length=150, null=True)),
                ('week4', models.CharField(max_length=150, null=True)),
                ('week5', models.CharField(max_length=150, null=True)),
                ('week6', models.CharField(max_length=150, null=True)),
                ('week7', models.CharField(max_length=150, null=True)),
                ('week8', models.CharField(max_length=150, null=True)),
                ('week9', models.CharField(max_length=150, null=True)),
                ('week10', models.CharField(max_length=150, null=True)),
                ('week11', models.CharField(max_length=150, null=True)),
                ('week12', models.CharField(max_length=150, null=True)),
                ('week13', models.CharField(max_length=150, null=True)),
                ('week14', models.CharField(max_length=150, null=True)),
                ('week15', models.CharField(max_length=150, null=True)),
                ('week16', models.CharField(max_length=150, null=True)),
                ('week17', models.CharField(max_length=150, null=True)),
                ('week18', models.CharField(max_length=150, null=True)),
                ('week19', models.CharField(max_length=150, null=True)),
                ('week20', models.CharField(max_length=150, null=True)),
                ('week21', models.CharField(max_length=150, null=True)),
                ('week22', models.CharField(max_length=150, null=True)),
                ('week23', models.CharField(max_length=150, null=True)),
                ('week24', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
