# Generated by Django 4.0.6 on 2023-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(default=0)),
                ('eliminated', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
    ]
