# Generated by Django 4.0.6 on 2023-01-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_rename_englist_review_manifest_english_review'),
        ('Advisors', '0002_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.batch'),
        ),
    ]
